<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>__LABEL__</string>
    <key>ProgramArguments</key>
    <array>
      <string>__CMDR_BIN__</string>
      <string>start</string>
      <string>-f</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/cmdr.out.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/cmdr.err.log</string>
    <key>EnvironmentVariables</key>
    <dict>
      <key>PATH</key>
      <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin</string>
      <key>CMDR_CODE_DIR</key>
      <string>__CMDR_CODE_DIR__</string>
      <key>CMDR_OLLAMA_URL</key>
      <string>__CMDR_OLLAMA_URL__</string>
      <key>CMDR_OLLAMA_MODEL</key>
      <string>__CMDR_OLLAMA_MODEL__</string>
      <key>CMDR_SUMMARIZER</key>
      <string>__CMDR_SUMMARIZER__</string>
      <key>CMDR_MULTIPLEXER</key>
      <string>__CMDR_MULTIPLEXER__</string>
      <key>CMDR_TERMINAL_APP</key>
      <string>__CMDR_TERMINAL_APP__</string>
      <key>CMDR_EDITOR</key>
      <string>__CMDR_EDITOR__</string>
    </dict>
  </dict>
</plist>
