ALTER TABLE activity_buckets ADD COLUMN pi_total INTEGER NOT NULL DEFAULT 0;
ALTER TABLE activity_buckets ADD COLUMN pi_working INTEGER NOT NULL DEFAULT 0;
ALTER TABLE activity_buckets ADD COLUMN pi_waiting INTEGER NOT NULL DEFAULT 0;
ALTER TABLE activity_buckets ADD COLUMN pi_idle INTEGER NOT NULL DEFAULT 0;
ALTER TABLE activity_buckets ADD COLUMN pi_unknown INTEGER NOT NULL DEFAULT 0;
